title = "Tigera / Calico Documentation"

[languages]
[languages.en]
title = "Tigera / Calico Documentation"
description = "Tigera / Calico unified documentation"
languageName ="English"
# Weight used for sorting.
weight = 1

